version: '3'

services:
  postgres:
    image: postgres:latest
    build: ./postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
